### ISSUE TITLE
CCarousel components

### ISSUE THREAD

**Issue by Createwj** [Blackman99/casual-ui#1]
https://casual-ui-svelte.donsen.site/components/carousel/#interval&autoplay
**Suggest：** Can the mouse stay while temporarily scrolling

**Comment by Blackman99** [comment]
It's a great feature suggestion. ❤️

**Comment by Blackman99** [comment]
This feature is accomplished. [In this release](https://github.com/Blackman99/casual-ui/releases/tag/v0.1.6)
