### ISSUE TITLE
CDatePicker Component

### ISSUE THREAD

**Issue by JinghuiS** [Blackman99/casual-ui#2]
CDatePicker Failed to resolve import "casual-i18n"  
猜测：svelte-kit package 打包的时候应该不会把依赖转换引进来，如果只发布lib，组件依赖monorepo里其他项目的内容应该都没用了

**Comment by Blackman99** [comment]
可能需要考虑更改打包方式，取代svelte package，感谢反馈

**Comment by Blackman99** [comment]
This issue has been resolved in the new repo
https://github.com/Casual-UI/svelte
